/* tslint:disable */
/* eslint-disable */
/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/bulk-embeddings-api';
export * from './api/embeddings-api';
export * from './api/health-api';
export * from './api/multi-embeddings-api';
export * from './api/rerank-api';

