/* tslint:disable */
/* eslint-disable */
/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BodyStartBulkEmbeddingV1BulkEmbeddingsPost } from '../models';
// @ts-ignore
import { BulkEmbeddingJobResponse } from '../models';
// @ts-ignore
import { DownloadResultResponse } from '../models';
// @ts-ignore
import { HTTPValidationError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * BulkEmbeddingsApi - axios parameter creator
 * @export
 */
export const BulkEmbeddingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Download Result
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadResultPost: async (jobId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('downloadResultPost', 'jobId', jobId)
            const localVarPath = `/v1/bulk-embeddings/{job_id}/download-result`
                .replace(`{${"job_id"}}`, encodeURIComponent(String(jobId !== undefined ? jobId : `-job_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/bulk-embeddings/{job_id}/download-result',
                httpMethod: 'POST'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve Job
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJob: async (jobId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getJob', 'jobId', jobId)
            const localVarPath = `/v1/bulk-embeddings/{job_id}`
                .replace(`{${"job_id"}}`, encodeURIComponent(String(jobId !== undefined ? jobId : `-job_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/bulk-embeddings/{job_id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upload a file and get embeddings for each row
         * @summary Start Bulk Embedding
         * @param {Uint8Array | File | buffer.File} file 
         * @param {string} model 
         * @param {BodyStartBulkEmbeddingV1BulkEmbeddingsPost} bodyStartBulkEmbeddingV1BulkEmbeddingsPost 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileAndGetEmbeddings: async (file: Uint8Array | File | buffer.File, model: string, bodyStartBulkEmbeddingV1BulkEmbeddingsPost: BodyStartBulkEmbeddingV1BulkEmbeddingsPost, email?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadFileAndGetEmbeddings', 'file', file)
            // verify required parameter 'model' is not null or undefined
            assertParamExists('uploadFileAndGetEmbeddings', 'model', model)
            // verify required parameter 'bodyStartBulkEmbeddingV1BulkEmbeddingsPost' is not null or undefined
            assertParamExists('uploadFileAndGetEmbeddings', 'bodyStartBulkEmbeddingV1BulkEmbeddingsPost', bodyStartBulkEmbeddingV1BulkEmbeddingsPost)
            const localVarPath = `/v1/bulk-embeddings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();
            const addFormParam = async (name: string, data: any, isBinary: boolean, isPrimitiveType: boolean) => {
                if (isBinary) {
                    if (data instanceof Uint8Array) {
                        // Handle Buffer data
                        const filetype = await fromBuffer(data)
                        const filename = filetype === undefined ? name : `${name}.${filetype.ext}`
                        localVarFormParams.append(name, data as any, filename);
                    } else if ("name" in data) {
                        // File instances in browsers and Node.js have the
                        // "name" property "Duck typing" files to handle browser
                        // File class or Node.js File class
                        // Web: https://developer.mozilla.org/en-US/docs/Web/API/File
                        // Node.js: https://nodejs.org/api/buffer.html#new-bufferfilesources-filename-options
                        if (isBrowser()) {
                            // FormData in browser can accept File/Blob directly
                            localVarFormParams.append(name, data, data.name);
                        } else {
                            // FormData in Node.js can only accept raw Buffer so convert before passing
                            const bytes = await data.arrayBuffer()
                            const buffer = Buffer.from(bytes)
                            localVarFormParams.append(name, buffer, data.name);
                        }
                    }
                } else {
                    if (isPrimitiveType) {
                        /**
                         * FormData can only accept string or Blob so we need to convert
                         * non-string primitives to string. We also need to convert
                         */
                        if (typeof data === "object") {
                          localVarFormParams.append(name, JSON.stringify(data));
                        } else {
                          localVarFormParams.append(name, data);
                        }
                    } else {
                        if (isBrowser()) {
                            localVarFormParams.append(name, new Blob([JSON.stringify(data)], { type: "application/json" }))
                        } else {
                            localVarFormParams.append(name, JSON.stringify(data), { type: "application/json", filename: "data.json" });
                        }
                    }
                }
            }
            if (!isBrowser()) Object.assign(localVarHeaderParameter, localVarFormParams.getHeaders());

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (file !== undefined) {
                await addFormParam('file', file, true, true)
            }
    
            if (email !== undefined) {
                await addFormParam('email', email, false, true)
            }
    
            if (model !== undefined) {
                await addFormParam('model', model, false, true)
            }
    
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;
            requestBeforeHook({
                requestBody: bodyStartBulkEmbeddingV1BulkEmbeddingsPost,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/bulk-embeddings',
                httpMethod: 'POST'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BulkEmbeddingsApi - functional programming interface
 * @export
 */
export const BulkEmbeddingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BulkEmbeddingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Download Result
         * @param {BulkEmbeddingsApiDownloadResultPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadResultPost(requestParameters: BulkEmbeddingsApiDownloadResultPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DownloadResultResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadResultPost(requestParameters.jobId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Retrieve Job
         * @param {BulkEmbeddingsApiGetJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJob(requestParameters: BulkEmbeddingsApiGetJobRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkEmbeddingJobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJob(requestParameters.jobId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Upload a file and get embeddings for each row
         * @summary Start Bulk Embedding
         * @param {BulkEmbeddingsApiUploadFileAndGetEmbeddingsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFileAndGetEmbeddings(requestParameters: BulkEmbeddingsApiUploadFileAndGetEmbeddingsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkEmbeddingJobResponse>> {
            const bodyStartBulkEmbeddingV1BulkEmbeddingsPost: BodyStartBulkEmbeddingV1BulkEmbeddingsPost = {
                file: requestParameters.file,
                email: requestParameters.email,
                model: requestParameters.model
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFileAndGetEmbeddings(requestParameters.file, requestParameters.model, bodyStartBulkEmbeddingV1BulkEmbeddingsPost, requestParameters.email, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * BulkEmbeddingsApi - factory interface
 * @export
 */
export const BulkEmbeddingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BulkEmbeddingsApiFp(configuration)
    return {
        /**
         * 
         * @summary Download Result
         * @param {BulkEmbeddingsApiDownloadResultPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadResultPost(requestParameters: BulkEmbeddingsApiDownloadResultPostRequest, options?: AxiosRequestConfig): AxiosPromise<DownloadResultResponse> {
            return localVarFp.downloadResultPost(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve Job
         * @param {BulkEmbeddingsApiGetJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJob(requestParameters: BulkEmbeddingsApiGetJobRequest, options?: AxiosRequestConfig): AxiosPromise<BulkEmbeddingJobResponse> {
            return localVarFp.getJob(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Upload a file and get embeddings for each row
         * @summary Start Bulk Embedding
         * @param {BulkEmbeddingsApiUploadFileAndGetEmbeddingsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileAndGetEmbeddings(requestParameters: BulkEmbeddingsApiUploadFileAndGetEmbeddingsRequest, options?: AxiosRequestConfig): AxiosPromise<BulkEmbeddingJobResponse> {
            return localVarFp.uploadFileAndGetEmbeddings(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for downloadResultPost operation in BulkEmbeddingsApi.
 * @export
 * @interface BulkEmbeddingsApiDownloadResultPostRequest
 */
export type BulkEmbeddingsApiDownloadResultPostRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof BulkEmbeddingsApiDownloadResultPost
    */
    readonly jobId: string
    
}

/**
 * Request parameters for getJob operation in BulkEmbeddingsApi.
 * @export
 * @interface BulkEmbeddingsApiGetJobRequest
 */
export type BulkEmbeddingsApiGetJobRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof BulkEmbeddingsApiGetJob
    */
    readonly jobId: string
    
}

/**
 * Request parameters for uploadFileAndGetEmbeddings operation in BulkEmbeddingsApi.
 * @export
 * @interface BulkEmbeddingsApiUploadFileAndGetEmbeddingsRequest
 */
export type BulkEmbeddingsApiUploadFileAndGetEmbeddingsRequest = {
    
    /**
    * 
    * @type {Uint8Array | File | buffer.File}
    * @memberof BulkEmbeddingsApiUploadFileAndGetEmbeddings
    */
    readonly file: Uint8Array | File | buffer.File
    
    /**
    * 
    * @type {string}
    * @memberof BulkEmbeddingsApiUploadFileAndGetEmbeddings
    */
    readonly model: string
    
    /**
    * 
    * @type {string}
    * @memberof BulkEmbeddingsApiUploadFileAndGetEmbeddings
    */
    readonly email?: string
    
} & BodyStartBulkEmbeddingV1BulkEmbeddingsPost

/**
 * BulkEmbeddingsApiGenerated - object-oriented interface
 * @export
 * @class BulkEmbeddingsApiGenerated
 * @extends {BaseAPI}
 */
export class BulkEmbeddingsApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Download Result
     * @param {BulkEmbeddingsApiDownloadResultPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkEmbeddingsApiGenerated
     */
    public downloadResultPost(requestParameters: BulkEmbeddingsApiDownloadResultPostRequest, options?: AxiosRequestConfig) {
        return BulkEmbeddingsApiFp(this.configuration).downloadResultPost(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve Job
     * @param {BulkEmbeddingsApiGetJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkEmbeddingsApiGenerated
     */
    public getJob(requestParameters: BulkEmbeddingsApiGetJobRequest, options?: AxiosRequestConfig) {
        return BulkEmbeddingsApiFp(this.configuration).getJob(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upload a file and get embeddings for each row
     * @summary Start Bulk Embedding
     * @param {BulkEmbeddingsApiUploadFileAndGetEmbeddingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BulkEmbeddingsApiGenerated
     */
    public uploadFileAndGetEmbeddings(requestParameters: BulkEmbeddingsApiUploadFileAndGetEmbeddingsRequest, options?: AxiosRequestConfig) {
        return BulkEmbeddingsApiFp(this.configuration).uploadFileAndGetEmbeddings(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
