/* tslint:disable */
/* eslint-disable */
/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { EmbeddingsCreateRepresentationRequest } from '../models';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { InputProperty } from '../models';
// @ts-ignore
import { ModelEmbeddingOutput } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmbeddingsApi - axios parameter creator
 * @export
 */
export const EmbeddingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create embedding representations of the given input texts.
         * @summary Create Embedding
         * @param {EmbeddingsCreateRepresentationRequest} embeddingsCreateRepresentationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRepresentation: async (embeddingsCreateRepresentationRequest: EmbeddingsCreateRepresentationRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'embeddingsCreateRepresentationRequest' is not null or undefined
            assertParamExists('createRepresentation', 'embeddingsCreateRepresentationRequest', embeddingsCreateRepresentationRequest)
            const localVarPath = `/v1/embeddings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: embeddingsCreateRepresentationRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/embeddings',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(embeddingsCreateRepresentationRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmbeddingsApi - functional programming interface
 * @export
 */
export const EmbeddingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmbeddingsApiAxiosParamCreator(configuration)
    return {
        /**
         * Create embedding representations of the given input texts.
         * @summary Create Embedding
         * @param {EmbeddingsApiCreateRepresentationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRepresentation(requestParameters: EmbeddingsApiCreateRepresentationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelEmbeddingOutput>> {
            const embeddingsCreateRepresentationRequest: EmbeddingsCreateRepresentationRequest = requestParameters;
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRepresentation(embeddingsCreateRepresentationRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmbeddingsApi - factory interface
 * @export
 */
export const EmbeddingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmbeddingsApiFp(configuration)
    return {
        /**
         * Create embedding representations of the given input texts.
         * @summary Create Embedding
         * @param {EmbeddingsApiCreateRepresentationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRepresentation(requestParameters: EmbeddingsApiCreateRepresentationRequest, options?: AxiosRequestConfig): AxiosPromise<ModelEmbeddingOutput> {
            return localVarFp.createRepresentation(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createRepresentation operation in EmbeddingsApi.
 * @export
 * @interface EmbeddingsApiCreateRepresentationRequest
 */
export type EmbeddingsApiCreateRepresentationRequest = {
    
} & EmbeddingsCreateRepresentationRequest

/**
 * EmbeddingsApiGenerated - object-oriented interface
 * @export
 * @class EmbeddingsApiGenerated
 * @extends {BaseAPI}
 */
export class EmbeddingsApiGenerated extends BaseAPI {
    /**
     * Create embedding representations of the given input texts.
     * @summary Create Embedding
     * @param {EmbeddingsApiCreateRepresentationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmbeddingsApiGenerated
     */
    public createRepresentation(requestParameters: EmbeddingsApiCreateRepresentationRequest, options?: AxiosRequestConfig) {
        return EmbeddingsApiFp(this.configuration).createRepresentation(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
