/* tslint:disable */
/* eslint-disable */
/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { DocumentsProperty } from '../models';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { QueryProperty } from '../models';
// @ts-ignore
import { RankingOutput } from '../models';
// @ts-ignore
import { TextRankInput } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * RerankApi - axios parameter creator
 * @export
 */
export const RerankApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Rank pairs.
         * @summary Rank
         * @param {TextRankInput} textRankInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pairRanking: async (textRankInput: TextRankInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'textRankInput' is not null or undefined
            assertParamExists('pairRanking', 'textRankInput', textRankInput)
            const localVarPath = `/v1/rerank`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: textRankInput,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/rerank',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(textRankInput, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RerankApi - functional programming interface
 * @export
 */
export const RerankApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RerankApiAxiosParamCreator(configuration)
    return {
        /**
         * Rank pairs.
         * @summary Rank
         * @param {RerankApiPairRankingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pairRanking(requestParameters: RerankApiPairRankingRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RankingOutput>> {
            const textRankInput: TextRankInput = {
                model: requestParameters.model,
                query: requestParameters.query,
                documents: requestParameters.documents,
                top_n: requestParameters.top_n,
                return_documents: requestParameters.return_documents
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.pairRanking(textRankInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RerankApi - factory interface
 * @export
 */
export const RerankApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RerankApiFp(configuration)
    return {
        /**
         * Rank pairs.
         * @summary Rank
         * @param {RerankApiPairRankingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pairRanking(requestParameters: RerankApiPairRankingRequest, options?: AxiosRequestConfig): AxiosPromise<RankingOutput> {
            return localVarFp.pairRanking(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for pairRanking operation in RerankApi.
 * @export
 * @interface RerankApiPairRankingRequest
 */
export type RerankApiPairRankingRequest = {
    
} & TextRankInput

/**
 * RerankApiGenerated - object-oriented interface
 * @export
 * @class RerankApiGenerated
 * @extends {BaseAPI}
 */
export class RerankApiGenerated extends BaseAPI {
    /**
     * Rank pairs.
     * @summary Rank
     * @param {RerankApiPairRankingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RerankApiGenerated
     */
    public pairRanking(requestParameters: RerankApiPairRankingRequest, options?: AxiosRequestConfig) {
        return RerankApiFp(this.configuration).pairRanking(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
