/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiSchemasRankUsage
 */
export interface ApiSchemasRankUsage {
    /**
     * The number of tokens used by all the texts in the input
     * @type {number}
     * @memberof ApiSchemasRankUsage
     */
    'total_tokens': number;
    /**
     * Same as total_tokens
     * @type {number}
     * @memberof ApiSchemasRankUsage
     */
    'prompt_tokens': number;
}

