/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InputProperty1 } from './input-property1';

/**
 * The input to the API for text embedding. OpenAI compatible
 * @export
 * @interface ApiSchemasEmbeddingTextEmbeddingInput
 */
export interface ApiSchemasEmbeddingTextEmbeddingInput {
    /**
     * The identifier of the model.  Available models and corresponding param size and dimension: - `jina-embedding-t-en-v1`, 14m, 312 - `jina-embedding-s-en-v1`, 35m, 512 (default) - `jina-embedding-b-en-v1`, 110m, 768 - `jina-embedding-l-en-v1`, 330, 1024  For more information, please checkout our [technical blog](https://arxiv.org/abs/2307.11224). 
     * @type {string}
     * @memberof ApiSchemasEmbeddingTextEmbeddingInput
     */
    'model': string;
    /**
     * 
     * @type {InputProperty1}
     * @memberof ApiSchemasEmbeddingTextEmbeddingInput
     */
    'input': InputProperty1;
    /**
     * The format in which you want the embeddings to be returned.Possible value are `float` and `base64`. Defaults to `float`
     * @type {string}
     * @memberof ApiSchemasEmbeddingTextEmbeddingInput
     */
    'encoding_format'?: ApiSchemasEmbeddingTextEmbeddingInputEncodingFormatEnum;
}

type ApiSchemasEmbeddingTextEmbeddingInputEncodingFormatEnum = 'float' | 'base64'


