/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Document containing a text field
 * @export
 * @interface ApiSchemasRankTextDoc
 */
export interface ApiSchemasRankTextDoc {
    /**
     * The ID of the BaseDoc. This is useful for indexing in vector stores. If not set by user, it will automatically be assigned a random value
     * @type {string}
     * @memberof ApiSchemasRankTextDoc
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiSchemasRankTextDoc
     */
    'text': string;
}

