/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BodyStartBulkEmbeddingV1BulkEmbeddingsPost
 */
export interface BodyStartBulkEmbeddingV1BulkEmbeddingsPost {
    /**
     * 
     * @type {Uint8Array | File | buffer.File}
     * @memberof BodyStartBulkEmbeddingV1BulkEmbeddingsPost
     */
    'file': Uint8Array | File | buffer.File;
    /**
     * 
     * @type {string}
     * @memberof BodyStartBulkEmbeddingV1BulkEmbeddingsPost
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof BodyStartBulkEmbeddingV1BulkEmbeddingsPost
     */
    'model': string;
}

