/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BulkEmbeddingJobStatus } from './bulk-embedding-job-status';

/**
 * 
 * @export
 * @interface BulkEmbeddingJobResponse
 */
export interface BulkEmbeddingJobResponse {
    /**
     * The user ID of the user who created the job
     * @type {string}
     * @memberof BulkEmbeddingJobResponse
     */
    'user_id': string;
    /**
     * The name of the model to use
     * @type {string}
     * @memberof BulkEmbeddingJobResponse
     */
    'model_name': string;
    /**
     * The model package ARN
     * @type {string}
     * @memberof BulkEmbeddingJobResponse
     */
    'model_package_arn'?: string;
    /**
     * The status of the job
     * @type {BulkEmbeddingJobStatus}
     * @memberof BulkEmbeddingJobResponse
     */
    'status': BulkEmbeddingJobStatus;
    /**
     * The name of the input file
     * @type {string}
     * @memberof BulkEmbeddingJobResponse
     */
    'file_name': string;
    /**
     * The email of the user who created the job
     * @type {string}
     * @memberof BulkEmbeddingJobResponse
     */
    'user_email'?: string;
    /**
     * Time of creation of the job.
     * @type {string}
     * @memberof BulkEmbeddingJobResponse
     */
    'created_at'?: string;
    /**
     * Time of completion of the job.
     * @type {string}
     * @memberof BulkEmbeddingJobResponse
     */
    'completed_at'?: string;
    /**
     * The error message of the job
     * @type {string}
     * @memberof BulkEmbeddingJobResponse
     */
    'error'?: string;
    /**
     * The ID of the job
     * @type {string}
     * @memberof BulkEmbeddingJobResponse
     */
    '_id': string;
    /**
     * The number of tokens used for the job
     * @type {number}
     * @memberof BulkEmbeddingJobResponse
     */
    'used_token_count'?: number;
}

