/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiSchemasEmbeddingTextEmbeddingInput } from './api-schemas-embedding-text-embedding-input';
import { ImageEmbeddingInput } from './image-embedding-input';
import { InputProperty } from './input-property';

/**
 * @type EmbeddingsCreateRepresentationRequest
 * @export
 */
export type EmbeddingsCreateRepresentationRequest = ApiSchemasEmbeddingTextEmbeddingInput | ImageEmbeddingInput;


