/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ImageDoc } from './image-doc';

/**
 * @type InputProperty
 * List of images to embed
 * @export
 */
export type InputProperty = Array<ImageDoc> | ImageDoc;


