/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiSchemasEmbeddingUsage } from './api-schemas-embedding-usage';

/**
 * Output of the embedding service
 * @export
 * @interface ModelEmbeddingOutput
 */
export interface ModelEmbeddingOutput {
    /**
     * The identifier of the model.  Available models and corresponding param size and dimension: - `jina-embedding-t-en-v1`, 14m, 312 - `jina-embedding-s-en-v1`, 35m, 512 (default) - `jina-embedding-b-en-v1`, 110m, 768 - `jina-embedding-l-en-v1`, 330, 1024  For more information, please checkout our [technical blog](https://arxiv.org/abs/2307.11224). 
     * @type {string}
     * @memberof ModelEmbeddingOutput
     */
    'model': string;
    /**
     * 
     * @type {string}
     * @memberof ModelEmbeddingOutput
     */
    'object'?: string;
    /**
     * A list of Embedding Objects returned by the embedding service
     * @type {Array<any>}
     * @memberof ModelEmbeddingOutput
     */
    'data': Array<any>;
    /**
     * Total usage of the request. Sums up the usage from each individual input
     * @type {ApiSchemasEmbeddingUsage}
     * @memberof ModelEmbeddingOutput
     */
    'usage': ApiSchemasEmbeddingUsage;
}

