/*
The Jina Embedding Serving API

This is the UniversalAPI to access all the Jina embedding models

The version of the OpenAPI document: 0.0.86


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiSchemasRankTextDoc } from './api-schemas-rank-text-doc';

/**
 * @type QueryProperty
 * The search query
 * @export
 */
export type QueryProperty = string | ApiSchemasRankTextDoc;


